name: Licensed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: puzl-ubuntu-latest
    name: Check licenses
    steps:
      - uses: actions/checkout@v6
      - run: npm ci
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - run: sudo apt-get update && sudo apt-get install -y build-essential cmake
      - run: gem install licensed:2.12.2 --no-document
      - run: licensed status
