name: Tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'
      
env:
  __PUZL_PUB_CACHE_IS_AVAILABLE: "true"
  
jobs:
  # Build and unit test
  static-tests:
    runs-on: [puzl-cloud]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: npm
    - run: npm ci
    - name: Prettier Format Check
      run: npm run format-check
    - name: ESLint Check
      run: npm run lint
    - name: Build & Test
      run: npm run test

  # End to end save and restore
  test-save:
    runs-on: [puzl-cloud]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Generate files in working directory
      shell: bash
      run: bash __tests__/create-cache-files.sh ${{ runner.os }} test-cache
    - name: Generate files outside working directory
      shell: bash
      run: bash __tests__/create-cache-files.sh ${{ runner.os }} ~/test-cache
    - name: Generate files outside working directory
      shell: bash
      run: bash __tests__/create-cache-files.sh ${{ runner.os }} ./test/dir/dist
    - name: Save cache
      uses: ./
      with:
        key: test-${{ runner.os }}-${{ github.run_id }}
        path: |
          test-cache
          ./test/**/dist
          ~/test-cache
    - name: tree /.puzl
      shell: bash
      run: tree /.puzl

  test-restore:
    needs: test-save
    runs-on: [puzl-cloud]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: tree /.puzl
      shell: bash
      run: tree /.puzl
    - name: Restore cache
      uses: ./
      with:
        key: test-${{ runner.os }}-${{ github.run_id }}
    - name: Verify cache files in working directory
      shell: bash
      run: bash __tests__/verify-cache-files.sh ${{ runner.os }} test-cache
    - name: Verify cache files outside working directory
      shell: bash
      run: bash __tests__/verify-cache-files.sh ${{ runner.os }} ./test/dir/dist
    - name: Verify cache files outside working directory
      shell: bash
      run: bash __tests__/verify-cache-files.sh ${{ runner.os }} ~/test-cache

  test-cleanup:
    needs: test-restore
    runs-on: [puzl-cloud]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cleanup old caches
      shell: bash
      run: bash -x cleanup.sh

  test-save-only:
    runs-on: [ puzl-cloud ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate files
        shell: bash
        run: bash __tests__/create-cache-files.sh ${{ runner.os }} test-separate-actions
      - name: Save cache (save-only)
        uses: ./save
        with:
          key: test-save-only-${{ runner.os }}-${{ github.run_id }}
          path: test-separate-actions
      - name: tree /.puzl
        shell: bash
        run: tree /.puzl

  test-restore-only:
    needs: test-save-only
    runs-on: [ puzl-cloud ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: tree /.puzl
        shell: bash
        run: tree /.puzl
      - name: Restore cache (restore-only)
        uses: ./restore
        with:
          key: test-save-only-${{ runner.os }}-${{ github.run_id }}
          path: test-separate-actions
      - name: Verify restored files
        shell: bash
        run: bash __tests__/verify-cache-files.sh ${{ runner.os }} test-separate-actions

  test-cleanup-restore-only:
    needs: test-restore-only
    runs-on: [ puzl-cloud ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cleanup old caches
        shell: bash
        run: bash -x cleanup.sh
